# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Is Christ True?"
site_url: https://ischristtrue.com/
site_description: "Is Christ True?"
site_author: RS Christopher
docs_dir: src
site_dir: docs
dev_addr: 127.0.0.1:7000
copyright: Uncopyright &copy; 2023-2026 ~ R.St. Christopher
extra:
    generator: false
extra_css:
    - stylesheets/extra.css
theme:
    name: material
    features:
        - navigation.indexes
        - navigation.instant
        - navigation.footer
        - navigation.sections
        - navigation.tabs
        - navigation.top
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    logo: images/christ-logo-w.png
    favicon: images/favicon.png

nav:
    - About: 
        - index.md
        - Nature of Truth: truth.md
        - Who is Christ?: who-is-christ.md
    - Modern Views:
        - modern-views/index.md
        - Christianity: modern-views/christianity.md
        - Ecumenism: modern-views/ecumenism.md
        - Enlightenment: modern-views/enlightenment.md
        - Free Will: modern-views/free-will.md
        - Justification: modern-views/justification.md
        - Millennialism: modern-views/millennialism.md
        - Money and Wealth: modern-views/money-wealth.md
        - Morality: modern-views/morality.md
        - Nihilism: modern-views/nihilism.md
        - Problem of Evil: modern-views/problem-of-evil.md
        - Puritans: modern-views/puritans.md
        - Schisms: modern-views/schisms.md
        - Socialism: modern-views/socialism.md
        - Spiritualism: modern-views/spiritualism.md
        - Syncretism: modern-views/syncretism.md
    - Ancient Views:
        - ancient-views/index.md
        - Angels and Demons: ancient-views/angels-demons.md
        - Antichrist: ancient-views/antichrist.md
        - Apocrypha: ancient-views/apocrypha.md
        - Cosmology: ancient-views/cosmology.md
        - Creation: ancient-views/creation.md
        - Death: ancient-views/death.md
        - Didache: ancient-views/didache.md
        - Essence-Energies: ancient-views/essence-energies.md
        - Fall of Man: ancient-views/fall.md
        - Filioque: ancient-views/filioque.md
        - Iconoclasm: ancient-views/iconoclasm.md
        - Mediation: ancient-views/mediation.md
        - Metanoia: ancient-views/metanoia.md
        - Mysteries: ancient-views/mysteries.md
        - Order and Chaos: ancient-views/order-chaos.md
        - Prelest: ancient-views/prelest.md
        - Prophecy: ancient-views/prophecy.md
        - Redemption: ancient-views/redemption.md
        - Salvation: ancient-views/salvation.md
        - Sin: ancient-views/sin.md
        - Tradition: ancient-views/tradition.md
        - Trinity: ancient-views/trinity.md
    - Logos:
        - logos/index.md
        - 'Kenosis: Incarnation':
            - Annunciation: logos/annunciation.md
            - Visitation: logos/visitation.md
            - Nativity: logos/nativity.md
            - Presentation in the Temple: logos/presentation-in-the-temple.md
            - Finding in the Temple: logos/finding-in-the-temple.md
        - 'Kenosis: Ministry':
            - Baptism of Jesus: logos/baptism-of-jesus.md
            - Temptations: logos/temptations.md
            - Proclamation of the Kingdom: logos/proclamation-of-the-kingdom.md
            - Wedding at Cana: logos/wedding-at-cana.md
            - Ministry in Galilee: logos/ministry-in-galilee.md
            - Sermon on the Mount: logos/sermon-on-the-mount.md
            - Signs and Wonders: logos/signs-and-wonders.md
            - Transfiguration: logos/transfiguration.md
            - Journey to Jerusalem: logos/journey-to-jerusalem.md
            - Triumphal Entry: logos/triumphal-entry.md
            - Institution of the Eucharist: logos/institution-of-the-eucharist.md
        - 'Kenosis: Passion':
            - Agony in the Garden: logos/agony-in-the-garden.md
            - Scourging at the Pillar: logos/scourging-at-the-pillar.md
            - Crowning with Thorns: logos/crowning-with-thorns.md
            - Carrying of the Cross: logos/carrying-of-the-cross.md
            - Crucifixion: logos/crucifixion.md
            - Harrowing of Hell: logos/harrowing-of-hell.md
        - Exultation:
          - Resurrection: logos/resurrection.md
          - Ascension: logos/ascension.md
          - Descent of the Holy Spirit: logos/descent-of-the-holy-spirit.md
          - Dormition of the Theotokos: logos/dormition-of-the-theotokos.md
          - Coronation of the Theotokos: logos/coronation-of-the-theotokos.md
          - Second Coming: logos/second-coming.md
          - Final Judgment: logos/final-judgment.md
    - References: 
        - references/index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

